export const states = {
    'AK' : 'Alaska',
    'AL' : 'Alabama',
    'AR' : 'Arkansas',
    'AS' : 'American Samoa',
    'AZ' : 'Arizona',
    'CA' : 'California',
    'CO' : 'Colorado',
    'CT' : 'Connecticut',
    'DC' : 'District of Columbia',
    'DE' : 'Delaware',
    'FL' : 'Florida',
    'GA' : 'Georgia',
    'GU' : 'Guam',
    'HI' : 'Hawaii',
    'IA' : 'Iowa',
    'ID' : 'Idaho',
    'IL' : 'Illinois',
    'IN' : 'Indiana',
    'KS' : 'Kansas',
    'KY' : 'Kentucky',
    'LA' : 'Louisiana',
    'MA' : 'Massachusetts',
    'MD' : 'Maryland',
    'ME' : 'Maine',
    'MI' : 'Michigan',
    'MN' : 'Minnesota',
    'MO' : 'Missouri',
    'MS' : 'Mississippi',
    'MT' : 'Montana',
    'NC' : 'North Carolina',
    'ND' : 'North Dakota',
    'NE' : 'Nebraska',
    'NH' : 'New Hampshire',
    'NJ' : 'New Jersey',
    'NM' : 'New Mexico',
    'NV' : 'Nevada',
    'NY' : 'New York',
    'OH' : 'Ohio',
    'OK' : 'Oklahoma',
    'OR' : 'Oregon',
    'PA' : 'Pennsylvania',
    'PR' : 'Puerto Rico',
    'RI' : 'Rhode Island',
    'SC' : 'South Carolina',
    'SD' : 'South Dakota',
    'TN' : 'Tennessee',
    'TX' : 'Texas',
    'UT' : 'Utah',
    'VA' : 'Virginia',
    'VI' : 'Virgin Islands',
    'VT' : 'Vermont',
    'WA' : 'Washington',
    'WI' : 'Wisconsin',
    'WV' : 'West Virginia',
    'WY' : 'Wyoming'}

export const classCategories = {
    'aerial' : 'Aerial', 
    'barre' : 'Barre', 
    'bootcamp' : 'Bootcamp', 
    'boxing-kickboxing' : 'Boxing \/         Kickboxing', 
    'circuit-training' : 'Circuit Training', 
    'crossfit' : 'Crossfit', 
    'cycling' : 'Cycling', 
    'dance' : 'Dance', 
    'gymnastics' : 'Gymnastics', 
    'interval-training' : 'Interval Training', 
    'martial-arts' : 'Martial Arts', 
    'outdoor' : 'Outdoor', 
    'personal-training' : 'Personal Training', 
    'pilates' : 'Pilates', 
    'rock-climbing' : 'Rock Climbing'
}

export const mililaryTime = {
    '1' : '01:00', 
    '2' : '02:00', 
    '3' : '03:00', 
    '4' : '04:00', 
    '5' : '05:00', 
    '6' : '06:00', 
    '7' : '07:00', 
    '8' : '08:00', 
    '9' : '09:00', 
    '10' : '10:00', 
    '11' : '11:00', 
    '12' : '12:00', 
    '13' : '13:00', 
    '14' : '14:00', 
    '15' : '15:00', 
    '16' : '16:00', 
    '17' : '17:00', 
    '18' : '18:00', 
    '19' : '19:00', 
    '20' : '20:00', 
    '21' : '21:00', 
    '22' : '22:00', 
    '23' : '23:00', 
    '24' : '24:00'
}

export const initialFormValues = {
    coursename: '',
    type: '',
    date: '',
    starttime: 0,
    duration: '',
    intensitylevel: '',
    location: '',
    sizecapacity: '',
  }
export const gitHubUsers = [
    'code-dependent',
    'mjschuette4',
    '1like2learn',
    'ginxy13th',
    'kc0buk',
]
