export const states = {
    'Alaska' : 'Alaska',
    'Alabama' : 'Alabama',
    'Arkansas' : 'Arkansas',
    'American Samoa' : 'American Samoa',
    'Arizona' : 'Arizona',
    'California' : 'California',
    'Colorado' : 'Colorado',
    'Connecticut' : 'Connecticut',
    'District of Columbia' : 'District of Columbia',
    'Delaware' : 'Delaware',
    'Florida' : 'Florida',
    'Georgia' : 'Georgia',
    'Guam' : 'Guam',
    'Hawaii' : 'Hawaii',
    'Iowa' : 'Iowa',
    'Idaho' : 'Idaho',
    'Illinois' : 'Illinois',
    'Indiana' : 'Indiana',
    'Kansas' : 'Kansas',
    'Kentucky' : 'Kentucky',
    'Louisiana' : 'Louisiana',
    'Massachusetts' : 'Massachusetts',
    'Maryland' : 'Maryland',
    'Maine' : 'Maine',
    'Michigan' : 'Michigan',
    'Minnesota' : 'Minnesota',
    'Missouri' : 'Missouri',
    'Mississippi' : 'Mississippi',
    'Montana' : 'Montana',
    'North Carolina' : 'North Carolina',
    'North Dakota' : 'North Dakota',
    'Nebraska' : 'Nebraska',
    'New Hampshire' : 'New Hampshire',
    'New Jersey' : 'New Jersey',
    'New Mexico' : 'New Mexico',
    'Nevada' : 'Nevada',
    'New York' : 'New York',
    'Ohio' : 'Ohio',
    'Oklahoma' : 'Oklahoma',
    'Oregon' : 'Oregon',
    'Pennsylvania' : 'Pennsylvania',
    'Puerto Rico' : 'Puerto Rico',
    'Rhode Island' : 'Rhode Island',
    'South Carolina' : 'South Carolina',
    'South Dakota' : 'South Dakota',
    'Tennessee' : 'Tennessee',
    'Texas' : 'Texas',
    'Utah' : 'Utah',
    'Virginia' : 'Virginia',
    'Virgin Islands' : 'Virgin Islands',
    'Vermont' : 'Vermont',
    'Washington' : 'Washington',
    'Wisconsin' : 'Wisconsin',
    'West Virginia' : 'West Virginia',
    'Wyoming' : 'Wyoming'}

export const classCategories = {
    'Aerial' : 'Aerial', 
    'Barre' : 'Barre', 
    'Bootcamp' : 'Bootcamp', 
    'Combat' : 'Combat', 
    'Circuit Training' : 'Circuit Training', 
    'Crossfit' : 'Crossfit', 
    'Cycling' : 'Cycling', 
    'Dance' : 'Dance', 
    'Gymnastics' : 'Gymnastics', 
    'Interval Training' : 'Interval Training', 
    'Martial Arts' : 'Martial Arts', 
    'Outdoor' : 'Outdoor', 
    'Personal Training' : 'Personal Training', 
    'Pilates' : 'Pilates', 
    'Rock Climbing' : 'Rock Climbing'
}

export const mililaryTime = {
    '1' : '01:00', 
    '2' : '02:00', 
    '3' : '03:00', 
    '4' : '04:00', 
    '5' : '05:00', 
    '6' : '06:00', 
    '7' : '07:00', 
    '8' : '08:00', 
    '9' : '09:00', 
    '10' : '10:00', 
    '11' : '11:00', 
    '12' : '12:00', 
    '13' : '13:00', 
    '14' : '14:00', 
    '15' : '15:00', 
    '16' : '16:00', 
    '17' : '17:00', 
    '18' : '18:00', 
    '19' : '19:00', 
    '20' : '20:00', 
    '21' : '21:00', 
    '22' : '22:00', 
    '23' : '23:00', 
    '24' : '24:00'
}

export const initialFormValues = {
    coursename: '',
    type: '',
    date: '',
    starttime: 0,
    duration: '',
    intensitylevel: '',
    location: '',
    sizecapacity: '',
  }
export const gitHubUsers = [
    'code-dependent',
    'mjschuette4',
    '1like2learn',
    'ginxy13th',
    'kc0buk',
]
